language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "12"
  - "13"
os:
  - linux
  - osx

before_install:
  - npm install -g typescript
  - npm install -g mocha
  - node --version
  - npm --version
  - gcc --version
  - g++ --version
  - yarn --version

cache:
  yarn: true
  directories:
    - "node_modules"
