language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "8"
  - "9"
  - "10"
os:
  - linux
  - osx

before_install:
  - npm install -g typescript
  - npm install -g mocha
  - node --version
  - npm --version
  - gcc --version
  - g++ --version
  - yarn --version
  
cache:
  yarn: true
  directories:
    - "node_modules"
